# Copyright 2020 by Murray Altheim. All rights reserved. This file is part of
# the Robot Operating System project and is released under the "Apache Licence,
# Version 2.0". Please see the LICENSE file included as part of this package.
#
# YAML configuration for Robot Operating System (ROS) ..........................

flask:
    enabled: False                               # start flask web server?

pi:
    disable_leds: False                          # disable and re-enable Pi LEDs during operation?
    led_0_path:   '/sys/class/leds/led0/brightness'
    led_1_path:   '/sys/class/leds/led1/brightness'
    sudo_name:    'sudo'

rosd:
    switch_pin: 14                               # the GPIO pin connected to the 'enable' toggle switch
    led_pin: 27                                  # the GPIO pin connected to the status LED
    application: 'gamepad'                       # the application to start via daemon ('ros' or 'gamepad')
ros:
    wait_for_button_press: False                 # robot waits in standby mode until red button is pressed
    enable_self_shutdown: True                   # enables the robot to shut itself down (not good during demos)
    enable_player: False                         # enables sound player (disable if no hardware support)
    main_loop_delay_ms:    5000                  # main os loop (doesn't have effect on performance)
    geometry:
        wheel_diameter: 68.5                     # wheel diameter (mm)
        wheelbase: 160.0                         # wheelbase (mm)
        steps_per_rotation: 494                  # encoder steps per wheel rotation
    arbitrator:
        loop_delay_sec: 0.01                     # arbitrator loop delay (sec)
        ballistic_loop_delay_sec: 0.2            # loop delay for ballistic tasks (sec)
    battery:
        enable_messaging:   True                 # if True we enable low battery messages to be sent
        five_volt_a_channel:   2                 # AD channel for power supply A
        five_volt_b_channel:   1                 # AD channel for power supply B
        battery_channel:       0                 # AD channel for raw battery voltage
        raw_battery_threshold: 17.74             # raw and 5v regulator thresholds set from known measurements:
        low_5v_threshold:      4.75              # really 4.82v
        settle_count:          3                 # how many times should we sample before accepting a first value?
        loop_delay_sec:       15                 # loop delay (sec)
    temperature:
        warning_threshold: 75.0                  # temperature threshold, exceeding this generates a warning (nominal 80°C)
        max_threshold:     84.0                  # maximum allowable temperature threshold, exceeding this sends an event (nominal 85°C)
        loop_delay_sec:    15.0                  # loop delay (sec)
    video:
        enable_streaming: True                   # if True, stream video to a localhost HTTP server
        ctrl_lights: True                        # if True, permit video to control Matrix11x7 lights
        convert_mp4: True                        # if True, convert h264 source to mp4
        annotate: True                           # if True, include annotation on video
        title: 'NZPRG - KR01'                            # the title portion of the video annotation
        quality: -1                              # video quality: -1 for default; values between 1 (high) - 40 (low), typical between 20-25.
        remove_h264: False                       # if True, remove h264 video source after converting to mp4
        port: 8001                               # server port for streaming video
        width: 1600                              # video width
        height: 512                              # video height
#       width: 1280                              # video width
#       height: 720                              # video height
        framerate: 30                            # video framerate
        lux_threshold: 14                        # lux threshold for night mode
        dirname: 'videos'                        # the name of the output directory
        basename: 'vid'                          # the base name for output files
    nxp9dof:
        quaternion_accept: True                  # if true, we accept Quaternion alone once calibrated
        loop_delay_sec: 0.1                      # sensor loop delay (seconds)
    bno055:
        loop_delay_sec: 0.1                      # sensor loop delay (seconds)
        i2c_device: 1                            # I2C device bus number, equivalent to '/dev/i2c-1'
        pitch_trim:   0.00                       # trim adjustment on pitch
        roll_trim:    0.00                       # trim adjustment on roll
        heading_trim: 0.00                       # trim adjustment on heading
        sample_rate: 20                          # sample rate in Hz
    accelerometer:
        jitter_limit: 0.1                        # how much jitter is permitted whilst considered at rest
    lidar:
        min_angle: -40.0                         # minimum scan angle (clearance of bumper)
        max_angle:  40.0                         # maximum scan angle (clearance of bumper)
        play_sound: False                        # if True, play 'ping' sound during scanning
        degree_step: 5.0                         # resolution of scan
        step_delay_sec: 0.10                     # how long to linger at each degree step to permit a reading
#       tof_range: 'medium'                      # ToF range: performance, long, medium or short
        tof_range: 'performance'                 # ToF range: performance, long, medium or short
        reverse_movement: True                   # reverses the servo movement in case hardware is backwards
        double_sweep: False                      # if True sweeps in both directions
        servo_number: 1                          # use this servo
    wall_follower:
        port_angle: -90.0                        # port-facing scan angle
        starboard_angle: 90.0                    # starboard-facing scan angle
        tof_range: 'performance'                 # ToF range: performance, long, medium or short
        servo_number: 2                          # use this servo
    ultrasonic_scanner:
        min_angle: -90.0                         # minimum scan angle
        max_angle:  90.0                         # maximum scan angle
        degree_step: 5.0                         # resolution of scan
        use_raw_distance: True                   # use raw distance, faster than when filtered
        read_delay_sec: 0.01                     # how long to wait at position for reading
        servo_number: 2                          # use this servo
    cat_scan:
        active_angle:  -90.0                     # servo position with arm raised
        inactive_angle: 90.0                     # servo position with arm lowered
        pir_pin:      15                         # pin connected to PIR sensor
        servo_number: 3                          # use this servo
    servo1:
        center_offset: 0.0                       # used by lidar: offset necessary to center the servo at 0.0
    servo2:
        center_offset: 2.0                       # used by uscanner and wall follower: offset necessary to center the servo at 0.0
    servo3:
        center_offset: 0.0                       # offset necessary to center the servo at 0.0
    servo4:
        center_offset: 0.0                       # offset necessary to center the servo at 0.0
    button:
        pin:           21                        # pin connected to hardware button
        toggle:      True                        # toggle or momentary button
    status:
        led_pin:       27                        # pin connected to status LED
#   bumper:
#       port_pin:      21                        # pin connected to port bumper
#       center_pin:    19                        # pin connected to center bumper
#       starboard_pin: 13                        # pin connected to starboard bumper
#       upper_pin:      7                        # pin connected to upper bumper
#   infrared:
#       port_pin:           6                    # pin connected to port infrared
#       center_pin:         0                    # pin connected to center infrared (use zero if using LR IR)
#       stbd_pin:          16                    # pin connected to starboard infrared
#       port_side_pin:      5                    # pin connected to port side infrared
#       stbd_side_pin:     12                    # pin connected to starboard side infrared
#       use_long_range:    True                  # use analog long range IR for center instead of short range digital IR
    gamepad:
        enabled: True
        device_path: '/dev/input/event6'         # the path to the bluetooth gamepad on the pi
        loop_delay: 0.01                         # main loop delay
    gamepad_demo:
        enable_compass: False                    # if True, enable Compass
        enable_ifs: True                         # if True, enable IntegratedFrontSensor
        loop_delay_ms: 20                        # the intended loop delay in ms (limit on message queue)
    motors:
        # GPIO pins configured for A1, B1, A2 and B2
        rotary_encoder_a1_port: 22
        rotary_encoder_b1_port: 23
        rotary_encoder_a2_stbd: 17
        rotary_encoder_b2_stbd: 18
        reverse_motor_orientation:   False       # in case you wire something up backwards
        reverse_encoder_orientation: False       # ditto
        sample_rate: 10                          # how many pulses per encoder measurement?
        velocity_fudge_factor: 14.0              # convert raw velocity to approximate a percentage
        max_power_limit: 1.0                     # limit set on power sent to motors
        accel_loop_delay_sec: 0.10
        pid:
            enable_slew:    True
            enable_p:       True
            enable_i:       False
            enable_d:       True
#           kp:             0.0016
#           ki:             0.0010
#           kd:             0.00010
            kp:             0.0020
            ki:             0.0010
            kd:             0.00010
            clip_limit:     0.8                  # negative and positive power limit
            sample_freq_hz: 20
    slew:
        minimum_output: 0.00                     # lower limit of permitted output values
        maximum_output: 100.00                   # upper limit of permitted output values
    filewriter:
        extension: '.dat'                        # file extension (must include the dot)
        directory_name: 'data'                   # output directory name
        default_filename_prefix: 'motors'        # output directory name
        gnuplot_template_file: 'settings_slew_template.gp'  # template for gnuplot settings
        gnuplot_output_file: 'settings_slew.gp'  # output file for gnuplot settings
    io_expander:
        port_side_ir_pin:  10                    # pin connected to port side infrared
        port_ir_pin:        8                    # pin connected to port infrared
        center_ir_pin:     11                    # pin connected to center infrared
        stbd_ir_pin:        7                    # pin connected to starboard infrared
        stbd_side_ir_pin:   9                    # pin connected to starboard side infrared
        port_bmp_pin:       6                    # pin connected to port bumper
        center_bmp_pin:     3                    # pin connected to center bumper
        stbd_bmp_pin:       5                    # pin connected to starboard bumper
    integrated_front_sensor:
        device_id:  0x08                         # i2c hex address of slave device, must match Arduino's SLAVE_I2C_ADDRESS
        channel:       1                         # SMBus channel
        loop_delay_sec: 0.05                     # the loop delay for the integrated front sensor
        # hardware pin assignments:
        port_side_ir_pin:   1                    # pin connected to port side infrared
        port_ir_pin:        2                    # pin connected to port infrared
        center_ir_pin:      3                    # pin connected to center infrared
        stbd_ir_pin:        4                    # pin connected to starboard infrared
        stbd_side_ir_pin:   5                    # pin connected to starboard side infrared
        port_bmp_pin:       9                    # pin connected to port bumper
        center_bmp_pin:    10                    # pin connected to center bumper
        stbd_bmp_pin:      11                    # pin connected to starboard bumper
        # the analog sensor value used as event trigger thresholds:
        port_side_trigger_distance:     70.0     # port side analog IR sensor
        port_trigger_distance:          90.0     # port analog IR sensor
        center_trigger_distance:        60.0     # center analog IR sensor
        stbd_trigger_distance:          90.0     # starboard analog IR sensor
        stbd_side_trigger_distance:     70.0     # starboard side analog IR sensor
        # long distance:
        port_side_trigger_distance_far: 65.0     # port side analog IR sensor (far)
        port_trigger_distance_far:      60.0     # port analog IR sensor (far)
        center_trigger_distance_far:    60.0     # center analog IR sensor (far)
        stbd_trigger_distance_far:      60.0     # starboard analog IR sensor (far)
        stbd_side_trigger_distance_far: 65.0     # starboard side analog IR sensor (far)

    i2c_master:
        device_id:  0x08                         # i2c hex address of slave device, must match Arduino's SLAVE_I2C_ADDRESS
        channel:       1                         # SMBus channel
        assignments:                             # pin assignments: a pin number followed by:
#           0:  'AIN'                            # 'DIN' (digital input); 'DNP' (digital input, pullup); 'AIN' (analog input); or 'OUT' (output)
            1:  'AIN'
            2:  'AIN'
            3:  'AIN'
            4:  'AIN'
            5:  'AIN'
#           7:  'OUT'
            9:  'DNP'
            10: 'DNP'
            11: 'DNP'
#           12: 'DNP'
    features:
        ht0740: False
        placeholder: ''

